name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master
  release:
    types:
      - published

env:
  CIBW_SKIP: "cp27*"


jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: "Pull & update submodules recursively"
      run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
    - name: Install deps
      run: |
          python3 -m pip install pybind11==2.7.1 && mkdir boost && sudo apt-get install libboost-all-dev
          mkdir ./lib 
          cp /usr/lib/x86_64-linux-gnu/libboost_regex.so ./lib && cp /usr/lib/x86_64-linux-gnu/libboost_iostreams.so ./libs
    - name: Install boost
      uses: MarkusJx/install-boost@v2.0.0
      id: install-boost
      with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here: 
        # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
        boost_version: 1.72.0
        # OPTIONAL: Specify a platform version
        platform_version: 20.04
        # OPTIONAL: Specify a custom install location
        boost_install_dir: .

    # NOTE: If a boost version matching all requirements cannot be found,
    # this build step will fail
    # - name: Setup tmate session
      # uses: mxschmitt/action-tmate@v3
    - name: "Build Cmake"
      run: |
          mkdir build && cd build &&  cmake .. -DCMAKE_BUILD_TYPE=Release  -DTONGRAMS_USE_SANITIZERS=OFF -DEMPHF_USE_POPCOUNT=ON -DTONGRAMS_USE_POPCNT=ON -DTONGRAMS_USE_PDEP=ON && make -j12
      env:
        CIBW_SKIP: "cp27* cp35-*"

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - uses: pypa/cibuildwheel@v1.12.0


    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl



